"use client";

import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { Eye,EyeOff,Lock,User,ArrowRight } from "lucide-react";

const API_URL="/backend-api/auth";

export default function DetailsPage(){
 const router=useRouter();const [phoneNumber,setPhoneNumber]=useState("");const [authType,setAuthType]=useState("");const [name,setName]=useState("");const [password,setPassword]=useState("");const [confirmPassword,setConfirmPassword]=useState("");const [show,setShow]=useState(false);const [show2,setShow2]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{const p=sessionStorage.getItem("authPhoneNumber"),t=sessionStorage.getItem("authAuthType");if(!p||!t)return router.replace("/auth/number");setPhoneNumber(p);setAuthType(t);},[router]);
 const submit=async(e)=>{e.preventDefault();if(password.length<8)return setError("Password must be at least 8 characters.");if(authType==="REGISTER"&&!name.trim())return setError("Enter your name.");if(authType==="REGISTER"&&password!==confirmPassword)return setError("Passwords do not match.");setLoading(true);setError("");try{const isLogin=authType==="LOGIN";const r=await fetch(API_URL+(isLogin?"/login":"/register"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(isLogin?{phoneNumber,password}:{phoneNumber,name:name.trim(),password,confirmPassword})});const d=await r.json();if(!r.ok||!d?.success)throw new Error(d?.message||"Authentication failed.");if(isLogin){localStorage.setItem("accessToken",d.accessToken);localStorage.setItem("refreshToken",d.refreshToken);localStorage.setItem("authUser",JSON.stringify(d.user));window.dispatchEvent(new Event("auth-change"));router.replace("/");}else{sessionStorage.setItem("authOtpPurpose","REGISTER");router.push("/auth/verify-otp");}}catch(e){setError(e?.message||"Authentication failed.");}finally{setLoading(false);}};
 return <main className="min-h-screen bg-[#f4f3ef] flex items-center justify-center p-5"><div className="w-full max-w-md"><button onClick={()=>router.back()} className="mb-6 text-sm font-bold">← Back</button><div className="mb-7"><div className="text-xs font-bold tracking-[.2em] text-zinc-500">DNS ACADEMY</div><h1 className="mt-3 text-4xl font-black">{authType==="LOGIN"?"Welcome back":"Create account"}</h1><p className="mt-2 text-zinc-500">{phoneNumber}</p></div><form onSubmit={submit} className="rounded-3xl bg-white p-6 border border-zinc-200 shadow-[0_20px_60px_rgba(0,0,0,.08)]">{authType==="REGISTER"&&<div className="mb-5"><label className="text-sm font-bold">Name</label><div className="mt-2 flex rounded-2xl border border-zinc-300 bg-zinc-50"><div className="px-4 flex items-center border-r border-zinc-300"><User size={17}/></div><input value={name} onChange={e=>setName(e.target.value)} className="w-full px-4 py-4 bg-transparent outline-none" placeholder="Your name"/></div></div>}<label className="text-sm font-bold">Password</label><div className="mt-2 flex rounded-2xl border border-zinc-300 bg-zinc-50"><div className="px-4 flex items-center border-r border-zinc-300"><Lock size={17}/></div><input type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} className="w-full px-4 py-4 bg-transparent outline-none" placeholder="Minimum 8 characters"/><button type="button" onClick={()=>setShow(!show)} className="px-4">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div>{authType==="REGISTER"&&<div className="mt-5"><label className="text-sm font-bold">Confirm password</label><div className="mt-2 flex rounded-2xl border border-zinc-300 bg-zinc-50"><div className="px-4 flex items-center border-r border-zinc-300"><Lock size={17}/></div><input type={show2?"text":"password"} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} className="w-full px-4 py-4 bg-transparent outline-none" placeholder="Confirm password"/><button type="button" onClick={()=>setShow2(!show2)} className="px-4">{show2?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></div>}{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-2xl bg-black text-white py-4 font-bold flex items-center justify-center gap-2 disabled:opacity-40">{loading?"Please wait":authType==="LOGIN"?"Login":"Create account"}{!loading&&<ArrowRight size={18}/>}</button>{authType==="LOGIN"&&<button type="button" onClick={()=>router.push("/auth/forgot-password")} className="w-full mt-4 text-sm font-bold text-zinc-600">Forgot password?</button>}</form></div></main>;
}