"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Phone } from "lucide-react";

const API_URL="/backend-api/auth";

export default function NumberPage(){
 const router=useRouter();const [phoneNumber,setPhoneNumber]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 const submit=async(e)=>{e.preventDefault();if(phoneNumber.length!==10)return setError("Enter valid 10-digit mobile number.");setLoading(true);setError("");try{const r=await fetch(API_URL+"/start",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phoneNumber:"+91"+phoneNumber})});const d=await r.json();if(!r.ok||!d?.success)throw new Error(d?.message||"Unable to continue.");sessionStorage.setItem("authPhoneNumber","+91"+phoneNumber);sessionStorage.setItem("authAuthType",d.exists?"LOGIN":"REGISTER");router.push("/auth/details");}catch(e){setError(e?.message||"Unable to connect.");}finally{setLoading(false);}};
 return <main className="min-h-screen bg-[#f4f3ef] flex items-center justify-center p-5"><div className="w-full max-w-md"><div className="mb-8"><div className="text-xs font-bold tracking-[.2em] text-zinc-500">DNS ACADEMY</div><h1 className="mt-3 text-4xl font-black tracking-tight">Login or create account</h1><p className="mt-2 text-zinc-500">Use your mobile number to continue.</p></div><form onSubmit={submit} className="rounded-3xl bg-white p-6 shadow-[0_20px_60px_rgba(0,0,0,.08)] border border-zinc-200"><label className="text-sm font-bold">Mobile number</label><div className="mt-2 flex rounded-2xl border border-zinc-300 bg-zinc-50 overflow-hidden focus-within:border-black"><div className="px-4 flex items-center border-r border-zinc-300 font-bold text-sm">+91</div><input value={phoneNumber} maxLength={10} inputMode="numeric" onChange={e=>{setPhoneNumber(e.target.value.replace(/\D/g,"").slice(0,10));setError("");}} placeholder="10-digit mobile number" className="w-full px-4 py-4 bg-transparent outline-none"/></div>{error&&<p className="mt-3 text-sm text-red-600 font-medium">{error}</p>}<button disabled={loading||phoneNumber.length!==10} className="mt-6 w-full rounded-2xl bg-black text-white py-4 font-bold flex items-center justify-center gap-2 disabled:opacity-40">{loading?"Please wait":"Continue"}{!loading&&<ArrowRight size={18}/>}</button></form></div></main>;
}